name: Deploy Web to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'firebase.json'
      - 'firestore.rules'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Use Service Account if available
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ${GITHUB_WORKSPACE}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${GITHUB_WORKSPACE}/gcp-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase (Hosting + Firestore Rules)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Using Service Account via GOOGLE_APPLICATION_CREDENTIALS"
          else
            echo "Service Account not set. Falling back to FIREBASE_TOKEN"
          fi
          firebase deploy --only hosting:alfa-206d1,firestore:rules --project alfa-206d1


