name: Deploy Web to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'firebase.json'
      - 'firestore.rules'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Auth via Service Account (google-github-actions/auth@v2)
        if: ${{ env.FIREBASE_SERVICE_ACCOUNT != '' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase with Service Account
        if: ${{ env.FIREBASE_SERVICE_ACCOUNT != '' }}
        run: |
          echo "Using Service Account via google-github-actions/auth@v2"
          firebase deploy --only hosting:alfa-206d1,firestore:rules --project alfa-206d1

      - name: Deploy to Firebase with FIREBASE_TOKEN (fallback)
        if: ${{ env.FIREBASE_SERVICE_ACCOUNT == '' }}
        env:
          FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
        run: |
          echo "Service Account not set. Falling back to FIREBASE_TOKEN"
          firebase deploy --only hosting:alfa-206d1,firestore:rules --project alfa-206d1


